spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service

# actuator properties
management.endpoints.web.exposure.include=*
management.info.env.enabled=true


info.app.name=stripe-provider-service
info.app.version=1.0.0
info.app.description=Spring Boot Microservice for Payments


