server.port=8888
spring.application.name=payment-config-servers

# Pointing to your dedicated configuration repository
spring.cloud.config.server.git.uri=https://github.com/alameen2904/payment-config-repo.git

# We use 'main' as the default branch for properties
spring.cloud.config.server.git.default-label=main



# Force a pull on startup to ensure we have the latest
spring.cloud.config.server.git.clone-on-start=true